name: "Snyk Code Scan"

on:
  push:
  workflow_dispatch:

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Code Scan'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v1

      # Install and Authenticate to Snyk
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          snyk auth ${SNYK_TOKEN}
      # Run Snyk Code
      - name: Run Snyk Code
        run: |
          snyk code test --sarif  > results.sarif
        continue-on-error: false
      - name: Upload SARIF report to DDOG
        run: |
          npm install -g @datadog/datadog-ci
          datadog-ci sarif upload results.sarif --service vulnerabilities-snyk-test --env drodriguezhdez
        env:
          DD_SITE: datad0g.com
          DD_API_KEY: '${{secrets.DATADOG_STAGING_API_KEY}}'